version: "3"
services:
  client:
    image: node:12.18.4
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./mca-client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
  api:
    image: node:12.18.4
    ports:
      - 3000:3000
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=doggospass
      - PGDATABASE=doggos
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./mca-server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=doggos
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=doggospass
    volumes:
      - "dbdata2:/var/lib/postgresql/data"
      - "./db/:/docker-entrypoint-initdb.d/:ro"
volumes:
  dbdata2: